[package]
name = "idmap"
edition.workspace = true
license.workspace = true
homepage.workspace = true
version.workspace = true

[dependencies]
chelps.workspace = true
dbg.workspace = true
libc.workspace = true

[build-dependencies]
cc = "1.0.97"
bindgen = "0.69.4"
