[package]
name = "dbg"
edition.workspace = true
license.workspace = true
homepage.workspace = true
version.workspace = true

[build-dependencies]
bindgen = "0.69.4"

[dependencies]
chelps.workspace = true

[dev-dependencies]
tempfile = "3.12.0"
paste = "1.0.15"
