[package]
name = "config"
edition.workspace = true
license.workspace = true
homepage.workspace = true
version.workspace = true

[dependencies]
libc.workspace = true

[build-dependencies]
bindgen = "0.69.4"
